### ISSUE TITLE
Add configuration for each unique item this plugin swaps

### ISSUE THREAD

**Issue by asmith-personal** [raiyni/menu-swapper-extended#59] opened 2020-10-31 01:29 UTC
My goto example is teak logs. There are situations I want to left-click use teak logs, and currently the only way to get around this (that I know of) is to disable the entire plugin, which obviously isn't ideal.

**Comment by raiyni** [comment] 2020-10-31 02:45
duplicate of https://github.com/raiyni/menu-swapper-extended/issues/15

**Closed by raiyni** 2020-10-31 02:45 UTC
